"""Add data timestamp

Revision ID: 258131defca3
Revises: f6aa95f76f35
Create Date: 2024-08-23 21:36:14.972323

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "258131defca3"
down_revision: Union[str, None] = "f6aa95f76f35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accesstokens",
        sa.Column(
            "created_at",
            sa.Integer(),
            server_default=sa.text("(unix_timestamp())"),
            nullable=True,
        ),
    )
    op.add_column(
        "accesstokens",
        sa.Column(
            "updated_at",
            sa.Integer(),
            server_default=sa.text("(unix_timestamp())"),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.Integer(),
            server_default=sa.text("(unix_timestamp())"),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            sa.Integer(),
            server_default=sa.text("(unix_timestamp())"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("accesstokens", "updated_at")
    op.drop_column("accesstokens", "created_at")
    # ### end Alembic commands ###
