"""Add user's allowed scopes

Revision ID: 999e2dc16df6
Revises: 258131defca3
Create Date: 2024-08-25 14:21:12.281023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "999e2dc16df6"
down_revision: Union[str, None] = "258131defca3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userscopes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.Integer(),
            server_default=sa.text("(unix_timestamp())"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.Integer(),
            server_default=sa.text("(unix_timestamp())"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_userscopes_id"), "userscopes", ["id"], unique=False)
    op.create_index(op.f("ix_userscopes_scope"), "userscopes", ["scope"], unique=True)
    op.create_index(
        op.f("ix_userscopes_user_id"), "userscopes", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userscopes_user_id"), table_name="userscopes")
    op.drop_index(op.f("ix_userscopes_scope"), table_name="userscopes")
    op.drop_index(op.f("ix_userscopes_id"), table_name="userscopes")
    op.drop_table("userscopes")
    # ### end Alembic commands ###
