"""Add role collumn to users

Revision ID: bd7bb3dfe3a8
Revises: 999e2dc16df6
Create Date: 2024-09-19 21:22:44.302467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd7bb3dfe3a8"
down_revision: Union[str, None] = "999e2dc16df6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("role", sa.String(length=10), nullable=False, server_default="user"),
    )
    op.drop_column("users", "is_superadmin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.add_column(
        "users",
        sa.Column(
            "is_superadmin",
            sa.Boolean(),
            nullable=True,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###
